# Request the planner to run and return a path
std_msgs/Header header

# Set the bound mode of the robot to use in planner.
# Use extension to actual size. (default)
int32 EXTENDED_BOUND = 0
int32 RELAXED_BOUND = 1
int32 MIN_BOUND = 2
int32 EXACT_BOUND = 3
int32 NO_BOUND = 4
# Can only be used with one of above values. Check Params/BoundModeType for more details.
int32 bound_mode

# Set root pose if requires the planner starts planning from this root.
# Otherwise, set all to zero, planner will start at robot's current state.
geometry_msgs/Pose root_pose
---
int32 FORWARD = 0
int32 BACKWARD = 1
int32 HOMING = 2
int32 REPOSITIONING = 3
int32 AUTO_CUSTOM_PATH = 4
int32 MANUAL_CUSTOM_PATH = 5
# Status of the best path, take one of the above values.
int32 status

# Return actual bound mode used for planning
int32 planning_bound_mode

# Return best path.
geometry_msgs/Pose[] path
