"""Emit worlds/cave_box.sdf: a primitives-only stand-in for the SubT cave."""

W = []          # (name, x, y, z, sx, sy, sz)


def box(name, x, y, z, sx, sy, sz):
    W.append((name, x, y, z, sx, sy, sz))


T = 0.5         # wall thickness
H = 4.0         # ceiling height
HALF = H / 2.0

# Main gallery: 80 m along x, 8 m along y, centred on the origin.
LX, LY = 80.0, 8.0
box("floor", 0, 0, -T / 2, LX + 2 * T, 40.0, T)
box("ceiling", 0, 0, H + T / 2, LX + 2 * T, 40.0, T)
box("gallery_wall_south", 0, -LY / 2, HALF, LX, T, H)
box("gallery_end_west", -LX / 2, 0, HALF, T, LY, H)
box("gallery_end_east", LX / 2, 0, HALF, T, LY, H)

# North side of the gallery is broken by three 6 m openings into side chambers,
# so the exploration front has somewhere to go that is not a straight line.
openings = [(-24.0, 6.0), (0.0, 6.0), (24.0, 6.0)]
seg_start = -LX / 2
for i, (cx, w) in enumerate(openings):
    seg_end = cx - w / 2
    box(f"gallery_wall_north_{i}", (seg_start + seg_end) / 2, LY / 2,
        HALF, seg_end - seg_start, T, H)
    seg_start = cx + w / 2
box("gallery_wall_north_3", (seg_start + LX / 2) / 2, LY / 2, HALF,
    LX / 2 - seg_start, T, H)

# One chamber per opening: 14 x 12, walled on three sides.
for i, (cx, _) in enumerate(openings):
    cy = LY / 2 + 6.0
    box(f"chamber{i}_west", cx - 7.0, cy, HALF, T, 12.0, H)
    box(f"chamber{i}_east", cx + 7.0, cy, HALF, T, 12.0, H)
    box(f"chamber{i}_north", cx, cy + 6.0, HALF, 14.0 + T, T, H)
    box(f"chamber{i}_wall_w", cx - 4.5, LY / 2, HALF, 5.0, T, H)
    box(f"chamber{i}_wall_e", cx + 4.5, LY / 2, HALF, 5.0, T, H)
    # A pillar keeps the chamber from being a single convex blob, which is the
    # degenerate case for a volumetric-gain sampler.
    box(f"chamber{i}_pillar", cx, cy, HALF, 1.5, 1.5, H)

# Clutter along the gallery: raycasts have to hit something other than walls or
# the TSDF is four planes and the planner has no reason to prefer any direction.
for i, x in enumerate(range(-34, 36, 8)):
    y = 2.2 if i % 2 else -2.2
    box(f"rock_{i}", float(x), y, 0.6, 1.6, 1.6, 1.2)

body = "\n".join(
    f"""    <model name="{n}">
      <static>true</static>
      <pose>{x} {y} {z} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
          <material>
            <ambient>0.35 0.33 0.30 1</ambient>
            <diffuse>0.55 0.52 0.47 1</diffuse>
          </material>
        </visual>
      </link>
    </model>"""
    for (n, x, y, z, sx, sy, sz) in W
)

SDF = f"""<?xml version="1.0" ?>
<!--
  A cave-shaped world built entirely from primitives: an 80 m gallery with three
  side chambers, pillars and scattered rock, enclosed by a floor and ceiling.

  It exists because darpa_cave_01.sdf needs the ~3.9 GB subt_cave_sim model set,
  which is not vendored anywhere in this repository. This world needs nothing on
  GZ_SIM_RESOURCE_PATH, so `ros2 launch gbplanner_gz_sim gz_sim.launch.py
  world:=cave_box` is a complete simulation on a fresh checkout, and it is what
  the package's own verification runs against.

  It is closed on all sides on purpose. Voxblox only marks a voxel free when a
  ray passes through it and terminates on a surface; an open world leaves the
  lidar's 50 m rays ending in nothing, the map stays unknown, and the planner's
  volumetric gain has no gradient to follow.

  Generated by worlds/gen_cave_box.py. Change the geometry there and re-run it;
  do not hand-edit the 36 <model> blocks below.
-->
<sdf version="1.9">
  <world name="cave_box">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <gui fullscreen="0">
      <plugin filename="MinimalScene" name="3D View">
        <gz-gui>
          <title>3D View</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="string" key="state">docked</property>
        </gz-gui>
        <engine>ogre2</engine>
        <scene>scene</scene>
        <ambient_light>0.5 0.5 0.5</ambient_light>
        <background_color>0.6 0.6 0.65</background_color>
        <camera_pose>-14 -14 10 0 0.5 0.7</camera_pose>
      </plugin>
      <plugin filename="GzSceneManager" name="Scene Manager"/>
      <plugin filename="InteractiveViewControl" name="Interactive view control"/>
      <plugin filename="CameraTracking" name="Camera Tracking"/>
      <plugin filename="WorldControl" name="World control">
        <gz-gui>
          <property type="bool" key="showTitleBar">false</property>
          <property type="string" key="state">floating</property>
          <property type="double" key="height">72</property>
          <property type="double" key="width">121</property>
          <anchors target="3D View">
            <line own="left" target="left"/>
            <line own="bottom" target="bottom"/>
          </anchors>
        </gz-gui>
        <play_pause>true</play_pause>
        <step>true</step>
        <start_paused>false</start_paused>
        <service>/world/cave_box/control</service>
        <stats_topic>/world/cave_box/stats</stats_topic>
      </plugin>
      <plugin filename="EntityTree" name="Entity tree"/>
    </gui>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 20 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.2 -0.9</direction>
    </light>

{body}
  </world>
</sdf>
"""

import pathlib
out = pathlib.Path("/home/santal/git/gbplanner_ros2/sim/gbplanner_gz_sim/worlds/cave_box.sdf")
out.write_text(SDF)
print(out, len(W), "models", len(SDF), "bytes")
