<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>map_manager</name>
  <version>1.0.0</version>
  <description>Wrappers for mapping framework</description>

  <maintainer email="mihir.dharmadhikari@gmail.com">Mihir Dharmadhikari</maintainer>
  <maintainer email="tung.dang@nevada.unr.edu">Tung Dang</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>voxblox</depend>
  <depend>voxblox_ros</depend>
  <depend>planner_common</depend>
  <depend>eigen</depend>
  <depend>libpcl-all-dev</depend>
  <depend>libgoogle-glog-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
